export const alternateTimelineSpaceTravelWithoutSpacex = {
    id: "alternate-timeline-space-travel-without-spacex",
    title: "Alternate Timeline: Space Travel Without SpaceX",
    excerpt: "What a failed 2002 deal in Moscow means for spaceflight today, and how I ended up hooked on the story in the first place.",
    date: "July 30, 2026",
    category: "Spaceflight",
    readTime: 11,
    tags: ["SpaceX", "Spaceflight", "NASA", "Blue Origin", "interpretation"],
    content: `
  It was May 2020. I'd just moved to Pokhara, a kid straight out of home, dropped into a city, and suddenly there was unlimited wifi and a brand new phone waiting for me. I was terminally online within a week. I was in grade 11, and school had turned into online classes I attended off that same phone, no laptop, just a screen small enough to split in half when I needed to. Covid was the backdrop to all of this, and it had flattened the world into something unrecognizable: conspiracy theories, lockdown rules, everyone talking about a "new normal" nobody had actually agreed to. Except from where I was sitting, none of it felt real. Nobody in my circle, nobody in my area, had so much as caught it. So while the rest of the internet was in crisis mode, I was mostly just confused about why everyone thought this was such a big deal.
  
  That's when a strange post showed up while I was scrolling through socials, YouTube, maybe Twitter, I don't fully remember which. Something about a human test flight. I had basically no background in spaceflight, just the casual, ambient kind of knowledge at best: that NASA existed, something vague about Soyuz. If anything, I'd been spending more of that year easing into Western culture and music than anything to do with rockets. I clicked anyway, and got greeted with an absurdly long countdown clock and two astronauts, Bob and Doug, names I still remember clearly to this day, suited up and ready to fly to the ISS. My first thought was something like: has the world actually come to this already? Is it even ready for this?
  
  I waited for the stream. It got delayed. Weather, they said, at the landing site. Not the launch site. The landing site, hundreds of miles away, for a landing that hadn't even happened yet. I remember thinking that was such a strange concept: a rocket flight hinging on weather somewhere it hadn't even reached.
  
  The next day, SpaceX's first crewed test flight for NASA finally launched, May 30, 2020, and I watched the whole thing split-screen alongside my online class. Something in me just latched on. The second the stream ended, I started digging up everything I could find: SpaceflightNow, Everyday Astronaut, whatever else the internet had to offer. I needed a new hobby anyway, and this was, without question, the most exciting thing I'd stumbled into in a long time.
  
  But I don't think it was only the information that hooked me. It was the sheer swagger of the thing. A booster the height of a building landing itself upright on a drone ship in the middle of the ocean isn't just efficient engineering, it's the exact image I'd grown up seeing in science fiction and never expected to actually watch live, on a stream, from my bedroom. It felt less like following an aerospace company and more like getting a sneak preview of a future that wasn't supposed to arrive this early. That's the part that turned "interesting news story" into "thing I check every single day."
  
  ---
  
  But one question keeps coming back to me ever since, in different forms, over and over: what if I'd never come across that test flight? What if SpaceX didn't exist at all? What would spaceflight look like right now, what would the world look like right now, without it?
  
  Welcome to the alternate timeline. Let's see how far the speculation holds up.
  
  ## The Fork in the Road
  
  Here's the part that gets me every time I retell this: [SpaceX](https://www.spacex.com) almost didn't happen because of a rocket company that no longer exists. Back in 2001, Elon Musk wasn't trying to build a launch provider at all. He had a plan called Mars Oasis, a tiny greenhouse he wanted to send to Mars just to get the public excited about space again. To pull it off cheap, he flew to Moscow to try to buy a launch vehicle from a Russian outfit that converted old SS-18 missiles into rockets. The negotiation fell apart. On the flight home, instead of giving up on the idea, he decided to build the rocket company himself.
  
  That's it. That's the entire fork. A yes in that meeting, and there's no Falcon, no Starship, no Dragon, and as far as I can tell, no version of my Tuesday afternoon in May 2020 that involves a countdown clock at all.
  
  ## A Monopoly Nobody Disturbs
  
  Roll the clock forward to the mid-2000s in this other timeline. [United Launch Alliance](https://www.ulalaunch.com), the joint Boeing/Lockheed venture flying the [Atlas V](https://www.ulalaunch.com/rockets/atlas-v) and [Delta IV](https://www.ulalaunch.com/rockets/delta-iv), is the only game in town for U.S. government launches, and business is *very* good. Atlas V missions bring in around $200 million each, Delta IV Heavy flights over $400 million, and on top of that ULA gets paid "launch capability" fees just to remain available, hundreds of millions to a billion dollars a year, whether or not there's anything to launch.
  
  In our actual timeline, SpaceX blew this arrangement up by suing the Air Force in 2014 over sole-source contracting, started flying national security missions in 2018, and undercut ULA badly enough that ULA had to build a whole new rocket, [Vulcan Centaur](https://www.ulalaunch.com/rockets/vulcan-centaur), just to stay competitive. Without that pressure, there's no obvious reason ULA develops anything new. The one wrinkle: Atlas V's first stage runs on a Russian RD-180 engine, and that becomes politically untenable once Russia starts invading its neighbors. Maybe Atlas V gets re-engined. Maybe Vulcan gets built anyway on a slower, more relaxed timeline. Either way, ULA is almost certainly still charging premium, cost-plus prices with nobody undercutting them.
  
  ## The Geostationary Status Quo
  
  Over in the commercial satellite world, [Arianespace](https://www.arianespace.com) had spent decades as the default choice for geostationary comms satellites, flying two payloads per [Ariane 5](https://en.wikipedia.org/wiki/Ariane_5) mission at roughly $100M and $65M a seat. Russia's Proton rocket picked up the customers who didn't want to wait for an Ariane slot and could tolerate a rocket with a shakier reliability record.
  
  SpaceX entered that market in 2013, undercut Proton almost immediately, and started eating into Ariane 5's business too, pressure that eventually pushed Arianespace to develop the cheaper [Ariane 6](https://www.arianespace.com/vehicle/ariane-6/), which didn't fly until 2024 after years of delay. Without SpaceX, there's no reason for Ariane 6 to exist at all. Ariane 5 keeps dominating, Proton keeps picking up the overflow, and geostationary comms satellites stay the whole story, because the thing that actually broke that model wasn't a cheaper rocket. It was a different kind of constellation entirely.
  
  ## No Starlink, No Ripple Effect
  
  [Starlink](https://www.starlink.com) only makes economic sense if you can launch constantly and cheaply enough to keep replacing and expanding a constellation of thousands of small satellites. Take away Falcon 9's launch cadence and cost, and there's no version of that business plan that pencils out. Which means: no scrappy internet constellation showing up as wartime infrastructure in Ukraine, no rural connectivity option filling in where fiber will never reach, and (this is the one that gets me) probably no [Project Kuiper](https://www.amazon.com/projectkuiper) either [I mean amazon leo or zefflink😏], since Amazon's whole satellite-internet push was built in reaction to what Starlink proved was possible.
  
  The funding story runs even deeper than that. Before 2015, space was a genuinely hard sell to venture capital: companies like Skybox Imaging, Planet Labs, Rocket Lab, and Spire Global were scraping together tens of millions in a market nobody wanted to touch. Then SpaceX raised a billion dollars in a single round in 2015, OneWeb raised half a billion right after, and an entire generation of space-focused VC funds got created in the aftermath, funds that went on to seed most of the "New Space" companies that exist today. Without that moment, my guess is space-startup funding is still stuck at pre-2015 levels, and a huge share of the companies I've come to follow simply never got funded in the first place.
  
  ## The Companies Left Standing
  
  [Rocket Lab](https://www.rocketlabusa.com) probably still exists in this timeline: [Electron](https://www.rocketlabusa.com/launch/electron/) doing roughly 300kg to orbit for about $12 million is a genuinely good deal next to Northrop Grumman's air-launched [Pegasus](https://en.wikipedia.org/wiki/Pegasus_(rocket)) at 443kg for $40 million. If Rocket Lab is the only credible small-launch company left standing, there's a real chance it becomes something like a mini-SpaceX: soaking up government launch contracts, eventually developing a medium-lift rocket to compete directly with ULA.
  
  [Blue Origin](https://www.blueorigin.com) is the harder one to call. In our world, they flew [New Shepard](https://www.blueorigin.com/new-shepard) with humans in 2021 (matching an altitude record from 1961) and then jumped straight to a 45-ton-to-orbit heavy-lift rocket, [New Glenn](https://www.blueorigin.com/new-glenn), rather than building something medium-sized first. A lot of that roadmap reads like a company trying to catch up to what SpaceX had already proven possible, reusable boosters included. Remove that competitive pressure, and maybe Blue Origin picks more modest, more attainable goals. Or maybe Jeff Bezos wanted a heavy-lift reusable rocket regardless of what anyone else was doing. Genuinely hard to say.
  
  If I'm honest, Blue Origin is also the company in this whole story that frustrates me the most, SpaceX or no SpaceX. Bezos talks a good game about "paving the road to space" for the generations after him, but the follow-through rarely matches the rhetoric. The company can afford to just keep a project alive for years on Amazon money without ever being forced to move fast or take a real risk. It's not that they've done nothing : New Shepard flies, New Glenn eventually flew. It's that with the resources and the runway he's had, it feels like there should be so much more to show for it by now. What stings is the lobbying: suing NASA over HLS, pushing Congress to mandate dual providers, embedding themselves in the SLS-era procurement machinery. They didn't compete on speed. They competed on procedure—slowing the game until they could catch up. I'm not angry, just tired, because you recognize the pattern: a company built to extract value from the *idea* of space without the pressure to actually dominate it.
  
  ## NASA's Impossible Position
  
  This is where the counterfactual gets serious. The [Columbia](https://en.wikipedia.org/wiki/Space_Shuttle_Columbia_disaster) disaster in 2003 sped up the Shuttle's retirement, which finally happened in 2011, leaving NASA needing some other way to reach the station it had just finished building. In 2006, NASA's Commercial Orbital Transportation Services program picked two winners: SpaceX, and a company called Kistler Aerospace. In 2007, Kistler failed to meet its private-fundraising milestones and got replaced by Orbital Sciences. [Cargo Dragon](https://www.spacex.com/vehicles/dragon/) first flew to the ISS in 2012; Orbital's [Cygnus](https://en.wikipedia.org/wiki/Cygnus_(spacecraft)) followed in 2013. [Commercial Crew](https://www.nasa.gov/humans-in-space/commercial-space/commercial-crew-program/) awards to SpaceX and Boeing came in 2014; Crew Dragon flew astronauts in 2020, and Boeing's [Starliner](https://www.boeing.com/space/starliner) finally followed in 2024, still without becoming fully operational.
  
  The uncomfortable detail: the only reason COTS existed as an open competition at all is that SpaceX sued NASA over an earlier no-bid award that NASA had been about to hand [Kistler](https://en.wikipedia.org/wiki/Kistler_Aerospace) outright, a company that, despite having already filed for bankruptcy once, still had a former Apollo program veteran running it. Without SpaceX around to sue, Kistler likely gets the money uncontested, and given its actual track record, there's a real chance the whole commercial cargo program just quietly fails a few years later. No Cygnus. No Starliner. No commercial option at all.
  
  That leaves NASA in a genuinely bad spot: fully dependent on Russian Soyuz flights for crew, at growing political cost, at exactly the moment U.S.-Russia relations are at their worst point in decades. The only other card on the table is NASA's own [Constellation program](https://en.wikipedia.org/wiki/Constellation_program), the [Ares I](https://en.wikipedia.org/wiki/Ares_I) crew rocket and Ares V cargo rocket, which was estimated to cost nearly $1 billion per Ares I flight and got cancelled in 2010 for exactly that reason, replaced by Commercial Crew. In a world where Commercial Crew never gets off the ground either, NASA might have no real choice but to keep funding Constellation, or lean on [SLS](https://www.nasa.gov/humans-in-space/space-launch-system/) and [Orion](https://www.nasa.gov/humans-in-space/orion/), a combination that was never designed with ISS crew rotation in mind and is wildly expensive for the job.
  
  ## No Lunar Lander, Maybe No Landing
  
  [Artemis](https://www.nasa.gov/artemis/) doesn't get a Starship-based lunar lander in this timeline, obviously. Maybe Blue Origin's "National Team" proposal wins the lander contract outright instead of losing it. Maybe one of the traditional primes (Lockheed, Boeing, Northrop) picks it up. Either way, it almost certainly costs more and takes longer than what we've actually gotten. Which, given how delayed and cost-strained Artemis already is in the real 2026, might be the one part of this alternate timeline that doesn't actually look all that different.
  
  ## Tallying the Winners and Losers
  
  ULA comes out on top: a launch monopoly they never have to defend, government contracts they never have to compete for. The Space Force is the clear loser, paying billions more for the exact same missions with none of the competitive pressure that actually drove costs down in our world. Arianespace does well too, never needing to spend the money developing Ariane 6. Roscosmos keeps its Proton business and its Soyuz seat sales. And the entire "New Space" wave of startups, most of them, simply never gets funded, because the moment that convinced venture capital space was worth betting on never happens.
  
  ---
  
  As of this writing, in July 2026, the present looks almost surreal next to that first stream. SpaceX is a publicly traded company now, SPCX on the Nasdaq, the largest IPO in market history, valued north of two trillion dollars. Starship is still very much in the way of everything, it flew Flight 13 a few days ago and nailed every objective, heat shield included, while NASA races to get it flying astronauts before 2028. Jared Isaacman, who commanded Polaris Dawn (still, hands down, my favorite mission anyone has flown, first commercial spacewalk, highest Earth orbit since Apollo) is now the NASA Administrator. I genuinely don't know how to process that sentence.
  
  Two honest admissions, since this is my blog and I get to make them. One: I'm skeptical of the orbital data center idea Musk keeps floating, not because I doubt he could pull it off (I wouldn't bet against him at this point, that's just my own skepticism talking), but because it still reads more like a slide in a pitch deck than an actual engineering roadmap. Two: I get genuinely nervous every time Starship launches now, and not in a fun way. I've followed this rocket through enough fireballs and near-misses that the countdown clock still gives me the same knot in my stomach it did in 2020, except now it's dread instead of pure excitement.
  
  But underneath all of that, what I actually feel is higher expectations, not lower ones. Watching this industry pull off things that would've sounded like science fiction to eleventh-grade me is exactly why I still expect more from it, not less, Blue Origin included. I've seen how much can change when one company decides to actually try. I want to see what else is possible.
  `
  }